apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: Generated Node.js application
spec:
  type: service
  lifecycle: experimental
  owner: user:guest